.\" Copyright (c) [year] [your name]
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD: head/share/examples/mdoc/example.1 333391 2018-05-09 02:02:49Z imp $
.\"
.\" Note: The date here should be updated whenever a non-trivial
.\" change is made to the manual page.
.\" If I want to change "FreeBSD General Commands Manual" .Os is the macro
.Dd $Mdocdate$
.Dt POT 1
.Os
.Sh NAME
.Nm pot
.Nd "jail-based container framework for FreeBSD"
.Sh SYNOPSIS
.Nm
.Cm help
.Op Ar command
.Nm
.Cm version
.Op Fl hvq
.Pp
.Nm
.Cm config
.Op Fl hvq
.Op Fl g Ar name
.Nm
.Cm show
.Op Fl hv
.Op Fl a | Fl r | Fl p Ar potname
.Nm
.Cm info
.Op Fl hvqr
.Fl p potname
.Nm
.Cm list
.Op Fl vq
.Op Fl hpbfFa
.Pp
.Nm
.Cm init
.Op Fl h
.Op Fl v
.Nm
.Cm de-init
.Op Fl h
.Op Fl vf
.Nm
.Cm vnet-start
.Op Fl h
.Op Fl v
.Pp
.Nm
.Cm create-base
.Op Fl h
.Op Fl v
.Fl r Ar release
.Op Fl b Ar basename
.Nm
.Cm create-fscomp
.Op Fl h
.Op Fl v
.Fl f fname
.Nm
.Cm create
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Fl b Ar basename
.Op Fl l Op 0 Ns | Ns 1
.Op Fl i Ar network
.Op Fl s
.Op Fl d Ar dns
.Op Fl t Ar type
.Op Fl F
.Op Fl f Ar flavour
.Op Fl f Ar flavour
.Ar ...
.Nm
.Cm create
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Fl P Ar basepot
.Op Fl l Op 1 Ns | Ns 2
.Op Fl i Ar network
.Op Fl s
.Op Fl d Ar dns
.Op Fl t Ar type
.Op Fl F
.Op Fl f Ar flavour
.Op Fl f Ar flavour
.Ar ...
.Nm
.Cm destroy
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Op Fl f
.Op Fl r
.Nm
.Cm destroy
.Op Fl h
.Op Fl v
.Fl b Ar basename
.Op Fl f
.Op Fl r
.Pp
.Nm
.Cm clone-fscomp
.Op Fl h
.Op Fl v
.Fl f Ar fname-new
.Fl F Ar fname-clonable
.Nm
.Cm clone
.Op Fl h
.Op Fl v
.Fl p Ar potname-new
.Fl P Ar potname-clonable
.Op Fl i Ar network
.Op Fl f
.Nm
.Cm promote
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Nm
.Cm rename
.Op Fl h
.Op Fl v
.Fl p Ar oldname
.Fl n Ar newname
.Pp
.Nm
.Cm add-fscomp
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Fl f Ar fname
.Fl m Ar mountpoint
.Op Fl e
.Op Fl w
.Op Fl r
.Nm
.Cm add-dep
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Fl P Ar dependency-potname
.Nm
.Cm set-rss
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Fl C Ar cpuset
.Fl M Ar max-memory
.Nm
.Cm set-cmd
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Fl c Ar command
.Nm
.Cm export-ports
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Fl e Ar port
.Op Fl e Ar port
.Ar ...
.Pp
.Nm
.Cm snapshot
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Op Fl a
.Nm
.Cm snapshot
.Op Fl h
.Op Fl v
.Fl f Ar fname
.Nm
.Cm rollback
.Op Fl h
.Op Fl v
.Fl p Ar potname
.Op Fl a
.Nm
.Cm rollback
.Op Fl h
.Op Fl v
.Fl f Ar fname
.Pp
.Nm
.Cm start
.Op Fl h
.Op Fl v
.Op Fl s Ns | Ns Fl S
.Ar potname
.Nm
.Cm stop
.Op Fl h
.Op Fl v
.Ar potname
.Nm
.Cm term
.Op Fl h
.Op Fl v
.Op Fl f
.Ar potname
.Nm
.Cm run
.Op Fl h
.Op Fl v
.Ar potname
.\" This is a section
.Sh DESCRIPTION
This manual page explain the usage of the
.Nm
command.
.Pp
The options are as follows:
.Bl -tag -width ".Fl d Ar argument"
.It Fl a
Example optional
.Fl a
option.
.It Fl b
Example optional
.Fl b
option.
.It Fl c
Example optional
.Fl c
option.
.It Fl d Ar argument
Example optional
.Fl d
option with required argument
.Ar argument .
.It Ar file
Required argument
.Ar file .
.El
.Sh ENVIRONMENT
The
.Nm
command ignores the
.Ev EXAMPLE
environment variable.
.Sh FILES
.Bl -tag -width ".Pa /dev/null" -compact
.It Pa /dev/null
Example of a file in the
.Sx FILES
section.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
The following is an example of a typical usage
of the
.Nm
command:
.Pp
.Dl "example -abc -d xyzzy /dev/null"
.Sh DIAGNOSTICS
The command may fail for one of the following reasons:
.Bl -diag
.It "###>  This operation needs 'root' privilegies"
You have to be root to run this command.
.It "===>  some runtime information requires root privileges"
Running the command as root will show more information
.El
.Sh SEE ALSO
.Xr cpuset 1 ,
.Xr epair 4 ,
.Xr jail 8 ,
.Xr rctl 8 ,
.Xr zfs 8 ,
.Xr vimage 9
.Sh HISTORY
The
.Nm
manual page example first appeared in verions 0.7.0
.Sh AUTHORS
This
manual page was written by
.An Luca Pizzamiglio Aq Mt pizzamig@FreeBSD.org .
.Sh BUGS
No known bugs, but they are expected.
